apiVersion: v1
kind: Service
metadata:
  name: rails 
  labels:
    app: rails 
spec:
  ports:
    - port: 3000
  selector:
    app: rails
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  selector:
    matchLabels:
      app: rails
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - image: mangelajo/rails-tutorial 
        name: rails
        envFrom:
        - secretRef:
            name: postgres-config
        env:
         - name: RAILS_APP_HOST
           value: rails.rails-test.svc.cluster.local
         - name: POSTGRES_HOST
           value: postgres.rails-test.svc.cluster.local
         - name: SECRET_KEY_BASE 
           valueFrom:
             secretKeyRef:
               name: rails-config
               key: SECRET_KEY_BASE
        ports:
        - containerPort: 3000
          name: rails
        volumeMounts:
        - name: rails-persistent-storage
          mountPath: /app/storage
      volumes:
      - name: rails-persistent-storage
        persistentVolumeClaim:
          claimName: rails-storage-pv-claim
