apiVersion: v1
kind: Service
metadata:
  name: rails 
  labels:
    app: rails 
spec:
  ports:
    - port: 3000
  selector:
    app: rails
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-storage-pv-claim
  labels:
    app: rails 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  selector:
    matchLabels:
      app: rails
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - image: mangelajo/rails-tutorial 
        name: rails
        env:
         - name: SECRET_KEY_BASE 
           valueFrom:
             secretKeyRef:
               name: rails-config
               key: SECRET_KEY_BASE
        ports:
        - containerPort: 3000
          name: rails
        volumeMounts:
        - name: rails-persistent-storage
          mountPath: /app/storage
      volumes:
      - name: rails-persistent-storage
        persistentVolumeClaim:
          claimName: rails-storage-pv-claim
