name: city-music-image-push

on:
  push:
    branches: main
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to ghcr.io
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: echo $REPO_TOKEN | docker login ghcr.io -u mangelajo --password-stdin

      - name: Run buildx for the base image
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          if [[ "$CHANGED_FILES" == *"deployment/docker/base-image"* ]]; then
            cd deployment/docker/base-image
            docker buildx build \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              --output "type=image,push=true" \
              . -t ghcr.io/mangelajo/city-music-base \
              --cache-from ghcr.io/mangelajo/city-music-base
          else
            echo "Skipping base image build as the base image description didn't change"
          fi

      - name: Build image
        run: docker build . -t ghcr.io/mangelajo/city-music

      - name: Run tests
        run: docker run --rm --entrypoint "/app/docker-test.sh" ghcr.io/mangelajo/city-music

      - name: Run buildx for the application image
        run: |
            docker buildx build \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              --output "type=image,push=true" \
              . -t ghcr.io/mangelajo/city-music

