name: city-music-base-image-pr

on:
  pull_request:
    branches: main

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Pull existing image
        run: docker pull ghcr.io/mangelajo/city-music-base
      -
        name: Run Buildx
        run: |
          cd deployment/docker/base-image
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            . -t ghcr.io/mangelajo/city-music-base \
            --cache-from ghcr.io/mangelajo/city-music-base

